### ISSUE TITLE
No implementation found for method getSpeed 

### ISSUE THREAD

**Issue by gijominuscule** [Syed-Moiz-Ali/internet_speed_meter#1]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getSpeed on channel internet_speed_meter)
E/flutter (12406): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)

**Comment by Syed-Moiz-Ali** [comment]
use getCurrentInternetSpeed method insted of getSpeed
